GET http://localhost:3000/

###
GET http://localhost:3000/messages

###
POST http://localhost:3000/messages
Content-Type: application/json

{
    "message": "Cache this message"
}

###
DELETE http://localhost:3000/messages